name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ranitmondal/chat-backend:latest ./Backend
          docker push ranitmondal/chat-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ranitmondal/chat-frontend:latest ./Frontend
          docker push ranitmondal/chat-frontend:latest

      - name: Deploy to EC2 K3s Cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export KUBECONFIG=/home/ubuntu/.kube/config

            cd ~/Chat-application

            git pull origin main

            kubectl apply -f k8s/

            kubectl rollout restart deployment/backend -n chat-app
            kubectl rollout restart deployment/frontend -n chat-app

            kubectl rollout status deployment/backend -n chat-app
            kubectl rollout status deployment/frontend -n chat-app